wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.9
    cli_version: 0.20.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750754332
    t:
      3:
      - 4
      - 16
      - 42
      - 55
      4: 3.12.9
      5: 0.20.1
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 10
